[package]
name = "better-ilias"
version = "1.0.2"
description = "A program to navigate Ilias and sync files to the local filesystem"
authors = ["Sebastian Klähn"]
repository = "https://github.com/Septias/better-ilias"
default-run = "better-ilias"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[dependencies]
serde_json = "1.0"
tauri = { version = "1.2", features = [] }
itertools = "0.10"
lazy_static = "1.4"
open = "3.0"
env_logger = "0.10"
log = "0.4"
hyper-tls = "0.5"
scraper = "0.14"
urlencoding = "2.1"
anyhow = "1.0"
thiserror = "1.0"
futures = "0.3"
headless_chrome = {git="https://github.com/rust-headless-chrome/rust-headless-chrome.git", features = ["fetch"] }
failure = "*"

[dependencies.hyper]
features = ["client", "http1"]
version = "0.14"

[dependencies.serde]
features = ["rc", "derive"]
version = "1.0"

[dependencies.tokio]
features = ["fs", "macros"]
version = "1.24"

[dependencies.reqwest]
features = ["cookies", "blocking"]
version = "0.11"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
features = ["json"]
