[package]
name = "better-ilias"
version = "0.1.0"
description = "A program to navigate Ilias and sync files to the local filesystem"
authors = ["Sebastian Klähn"]
repository = "https://github.com/Septias/better-ilias"
default-run = "better-ilias"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1.1" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[package.metadata.winres]
FileDescription = "A program to navigate Ilias and sync files to the local filesystem"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
serde_json = "1.0"
tauri = { version = "1.1.1", features = ["api-all"] }
itertools = "*"
lazy_static = "1.4.0"
open = "3.0.3"
env_logger = "0.9.1"
log = "0.4.17"
hyper-tls = "0.5.0"
scraper = "0.13.0"
urlencoding = "2.1.2"
anyhow = "1.0.66"
thiserror = "1.0.24"
futures = "0.3.25"
tokio-tungstenite = "0.17.2"

[dependencies.hyper]
features = ["client", "http1"]
version = "0.14.22"

[dependencies.serde]
features = ["rc", "derive"]
version = "1.0.147"

[dependencies.tokio]
features = ["full"]
version = "1.21.2"

[dependencies.reqwest]
features = ["cookies", "blocking"]
version = "0.11.12"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
features = ["json"]
