[debug]
address = "127.0.0.1"
port = 2020

[release]
address = "127.0.0.1"
keep_alive = 5
limits = {forms = 32768}
port = 2020
read_timeout = 5
write_timeout = 5

[default.databases.sqlite_db]
url = "db.sqlite"